version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
  web:
    build: .
    command: bundle exec rails s -p 7000 -b '0.0.0.0'
    volumes:
      - .:/web-app-sample
    ports:
      - "7000:7000"
    depends_on:
      - db
